function prepareMenu( fig )
  labels = str2mat( ...
     '&File', ...
     '>&New^n', ...
     '>&Open^o', ...
     '>&Close', ...
     '>-------', ...
     '>&Save^s', ...
     '>Save As', ...
     '>-------', ...     
     '>&Exit menv^q', ...
     '&Solve', ...
     '>Matcher Parameters', ...
     '>Run Periodic Matcher', ...
     '>Run Matcher', ...
     '>-------', ...
     '>Beam Parameters', ...
     '>Compute Solution', ...
     '&Figure', ...
     '>Measure', ...
     '>-------', ...
     '>Import Figure', ...
     '>Clear Import', ...
     '>Export Figure', ...
     '&Plug-in', ...
     '>UMER:', ...
     '>>Kappa to Current', ...
     '>Reference Trajectory', ...
     '>> Draw','>>Load', ...
     '&Help', ...
     '>&About^a' ...
     );
  callbacks = str2mat( ...
     '', ...
     'menvEvent(''New'')', ...
     'menvEvent(''Open'')', ...
     'menvEvent(''Close'')', ...
     '', ...
     'menvEvent(''Save'')', ...
     'menvEvent(''SaveAs'')', ...
     '', ...
     'menvEvent(''Exit'')', ...
     '', ...
     'menvEvent(''MatcherParam'')', ...
     'menvEvent(''Run Periodic Matcher'')', ...
     'menvEvent(''Matcher'')', ...
     '', ...
     'menvEvent(''Param'')', ...
     'menvEvent(''Solution'')', ...
     '', ...
     'menvEvent(''Coordinate'')', ...
     '', ...
     'menvEvent(''Import'')', ...
     'menvEvent(''ClearImport'')', ...
     'menvEvent(''Export'')', ...     
     '', ...
     '', ...
     'menvEvent(''Kappa to Current'')', ...
     '', ...
     'menvEvent(''Draw Reference Trajectory'')', ...
     'menvEvent(''Load Reference Trajectory'')', ...
     '', ...
     'menvEvent(''About'')' ...
     );
  handles = makemenu( fig, labels, callbacks );
