function fig = defElement()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load defElement

h0 = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'FileName','defElement.m', ...
	'MenuBar','none', ...
	'Name','Define Element', ...
	'NumberTitle','off', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[414.75 434.25 324 84.75], ...
	'RendererMode','manual', ...
	'Resize','off', ...
	'Tag','DefElementFig', ...
	'ToolBar','none', ...
	'UserData','[ ]', ...
	'WindowStyle','modal');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.831372549019608 0.815686274509804 0.784313725490196], ...
	'Callback','menvEvent( ''OK'' );', ...
	'ListboxTop',0, ...
	'Position',[257.25 8.25 58.5 21], ...
	'String','OK', ...
	'Tag','ElementOKPushbutton');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.831372549019608 0.815686274509804 0.784313725490196], ...
	'Callback','menvEvent( ''Cancel'' );', ...
	'ListboxTop',0, ...
	'Position',[186 8.25 58.5 21], ...
	'String','Cancel', ...
	'Tag','ElementCancelPushbutton');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','menvEvent( ''ElementChange'' );', ...
	'ListboxTop',0, ...
	'Position',[8.25 37.5 47.25 18.75], ...
	'String',mat1, ...
	'Style','popupmenu', ...
	'Tag','ElementPopupMenu', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[69.75 39 48.75 17.25], ...
	'Style','edit', ...
	'Tag','LocationEditText');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[133.625 39 48.75 17.25], ...
	'Style','edit', ...
	'Tag','LengthEditText');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[197.0625 39 60.75 17.25], ...
	'Style','edit', ...
	'Tag','StrengthEditText', ...
	'UserData','[ ]');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[8.25 59.25 45 12.75], ...
	'String','Element', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[69.75 59.25 56.25 12.75], ...
	'String','Location(cm)', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[133.625 59.25 56.25 12.75], ...
	'String','Length(cm)', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[197.0625 59.25 60 12.75], ...
	'String','Kappa(1/m^2)', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[8.25 13.5 49.5 15.75], ...
	'String','Optimize', ...
	'Style','checkbox', ...
	'Tag','OptimCheckbox');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[272.5 39 42 17.25], ...
	'Style','edit', ...
	'Tag','DiplIndexEditText', ...
	'UserData','[ ]');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[272.5 59.25 45 12.75], ...
	'String','Dipl Index', ...
	'Style','text', ...
	'Tag','StaticText1');
if nargout > 0, fig = h0; end
