function fig = ImportOpt()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load ImportOpt

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'FileName','ImportOpt.m', ...
	'MenuBar','none', ...
	'Name','Import Options', ...
	'NumberTitle','off', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[519 334 337 150], ...
	'Resize','off', ...
	'Tag','ImportOptionsFig', ...
	'ToolBar','none', ...
	'WindowStyle','modal');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[12.75 37.5 81.75 58.5], ...
	'Style','frame', ...
	'Tag','Frame1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[21.75 87 65.25 17.25], ...
	'String','Data Units', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback',mat1, ...
	'ListboxTop',0, ...
	'Position',[38.25 70.5 39.75 15], ...
	'String','mm', ...
	'Style','radiobutton', ...
	'Tag','mmRadiobutton');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback',mat2, ...
	'ListboxTop',0, ...
	'Position',[38.25 55.5 39.75 15], ...
	'String','cm', ...
	'Style','radiobutton', ...
	'Tag','cmRadiobutton', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback',mat3, ...
	'ListboxTop',0, ...
	'Position',[38.25 40.5 39.75 15], ...
	'String','m', ...
	'Style','radiobutton', ...
	'Tag','mRadiobutton');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.831372549019608 0.815686274509804 0.784313725490196], ...
	'Callback','uiresume;', ...
	'ListboxTop',0, ...
	'Position',[14.25 8.25 54 20.25], ...
	'String','OK', ...
	'Tag','OKPushbutton');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontName','FixedWidth', ...
	'Position',[115.5 8.25 126.75 96.75], ...
	'String',' ', ...
	'Style','listbox', ...
	'Tag','PreviewListbox', ...
	'Value',1);
if nargout > 0, fig = h0; end
