function prepareMenu( fig )
  labels = str2mat( ...
     '&File', ...
     '>&New^n', ...
     '>&Open^o', ...
     '>&Close', ...
     '>-------', ...
     '>&Save^s', ...
     '>Save As', ...
     '>-------', ...     
     '>&Exit menv^q', ...
     '&Solve', ...
     '>Beam Parameters', ...
     '>Compute Solution', ...
     '&Optimize', ...
     '>Matcher Parameters', ...
     '>Run Periodic Matcher', ...
     '>Run Matcher', ...
     '>Run Global Search (beta)', ...
     '>Run Multi-Objective Search (beta)', ...
     '&Figure', ...
     '>Measure', ...
     '>-------', ...
     '>Import Figure', ...
     '>Clear Import', ...
     '>Export Figure', ...
     '&Plug-in', ...
     '>UMER:', ...
     '>>Kappa to Current', ...
     '>Reference Trajectory', ...
     '>> Draw','>>Load', ...
     '&Help', ...
     '>&About^a' ...
     );
  callbacks = str2mat( ...
     '', ...
     'menvEvent(''New'')', ...
     'menvEvent(''Open'')', ...
     'menvEvent(''Close'')', ...
     '', ...
     'menvEvent(''Save'')', ...
     'menvEvent(''SaveAs'')', ...
     '', ...
     'menvEvent(''Exit'')', ...
     '', ...
     'menvEvent(''Param'')', ...
     'menvEvent(''Solution'')', ...
     '', ...
     'menvEvent(''MatcherParam'')', ...
     'menvEvent(''Run Periodic Matcher'')', ...
     'menvEvent(''Matcher'')', ...
     'menvEvent(''Global Search'')', ...
     'menvEvent(''Multi-Objective'')', ...
     '', ...
     'menvEvent(''Coordinate'')', ...
     '', ...
     'menvEvent(''Import'')', ...
     'menvEvent(''ClearImport'')', ...
     'menvEvent(''Export'')', ...     
     '', ...
     '', ...
     'menvEvent(''Kappa to Current'')', ...
     '', ...
     'menvEvent(''Draw Reference Trajectory'')', ...
     'menvEvent(''Load Reference Trajectory'')', ...
     '', ...
     'menvEvent(''About'')' ...
     );
  handles = makemenu( fig, labels, callbacks );
